language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: bTt4z3xLSBtSreoKDlHuUsf4rAufSmeW9cfB3/hduOuN3rtq7l/OztycKVsoOwAln+QscKpsydmsgzrNtbLe+s4HtUiojqCMWxWkkI5WvOkBuatMWpt2xoQPWZxXhx3n4nDoOO4iV2xVWSCn9Mdg9ZDhps/buX6aXuvoqUhT0ks=
  - secure: ThT+7URsGZdtD0hgKFhjk/7MYGbRYyOF4lBVvBiI1bu8J9LtuipiChqDfLRYsnds6822ezEkLSrst8466EFwvcE0N+YNBPVpUiStDfPGOhvzvwj5/KXo2pEo2uWui7zuE6dgpbO6dNmU5UIf5KgXIdHL5z34i6nmmTyJPr7xTd4=
script: cd tests && bundle exec ckit brew
before_script:
  - bundle rackup   # start a Web server
  - sleep 3         # give Web server some time to bind to sockets, etc
addons:
  sauce_connect: true
notifications:
  hipchat: 2a07784c1aeed1b6efa332242d3fc3@Notifications
  email: false
